### ISSUE TITLE
Suggesting improvements regarding the Rotten Tomatoes private API

### ISSUE THREAD

**Issue by savandriy** [jaebradley/rotten_tomatoes_client#14]
Hi!

I've done some research on my part, and discovered a few interesting things about the Rotten Tomatoes private API. I guess you'd want to implement them :)

1. When browsing lists (for example, 'dvd-streaming-all'), you can specify the 'page' parameter, starting from 0. Example: 
```
https://www.rottentomatoes.com/api/private/v2.0/browse?type=dvd-streaming-all&page=0
```
2. By default, lists like 'dvd-streaming-all' display 32 results on one page. You can change this, using the 'limit' parameter. Example: 
```
https://www.rottentomatoes.com/api/private/v2.0/browse?type=dvd-streaming-all&page=0&limit=100
```
3. You can get detailed info on a specified movie like this 'https://www.rottentomatoes.com/api/private/v1.0/movies/{id}'. Example:
```
https://www.rottentomatoes.com/api/private/v1.0/movies/12911
```

Also, if while browsing a list you specify a page, that is out of range, you'll get this result:
```json
{"counts":{"count":0,"total":0},"results":[],"debugUrl":"http://rt-client-facade-v2-6-1.aws.prod.flixster.com/movie?expand=true&include=%5B%22movieSupplementaryInfo%22%2C%22audienceSummary%22%2C%22affiliates%22%2C%22criticSummary%22%2C%22moviePersonnel%22%2C%22moviePersonnel.actors%22%2C%22moviePersonnel.actors.person%22%5D&filter=%7B%22country%22%3A%22UA%22%2C%22search%22%3A%7B%22mpaa-rating-min%22%3A%22G%22%2C%22release-year-max%22%3A2017%2C%22filter-release-date%22%3A%22false%22%2C%22offset%22%3A319968%2C%22sort%22%3A%22DVD_RELEASE_DATE_DESC%22%2C%22distribution%22%3A%22ANY%22%2C%22tomatometer-min%22%3A0%2C%22mpaa-rating-max%22%3A%22UN%22%2C%22release-day-of-month-max%22%3A17%2C%22limit%22%3A32%2C%22release-month-max%22%3A8%2C%22tomatometer-max%22%3A100%2C%22use-dvd-date%22%3Atrue%2C%22status%22%3A%22LIVE%22%7D%7D"}
```
Using this 'debugUrl', you can get direct access to their servers on AWS :)
This is what this url looks like when decoded:
```
http://rt-client-facade-v2-6-1.aws.prod.flixster.com/movie?expand=true&include=["movieSupplementaryInfo","audienceSummary","affiliates","criticSummary","moviePersonnel","moviePersonnel.actors","moviePersonnel.actors.person"]&filter={"country":"UA","search":{"mpaa-rating-min":"G","release-year-max":2017,"filter-release-date":"false","offset":319968,"sort":"DVD_RELEASE_DATE_DESC","distribution":"ANY","tomatometer-min":0,"mpaa-rating-max":"UN","release-day-of-month-max":17,"limit":32,"release-month-max":8,"tomatometer-max":100,"use-dvd-date":true,"status":"LIVE"}}
```

P.S. Also, I discovered the private API for Flixster android app. I used [mitmproxy](https://mitmproxy.org/) and my Android phone with [SSLUnpinning2.0](https://github.com/ac-pm/SSLUnpinning_Xposed) installed. This API is very similar to Rotten Tomatoes API, and probably uses the same database (they have the same owner), as the movie IDs match. 
Example requests to Flixster API(get detailed info on movie with id of 12911):
```
https://api.flixster.com/android/api/v2/movies/12911.json
```
Just thought you may be interested.

**Comment by jaebradley** [comment]
Thanks for the great information @savandriy!

**Comment by jaebradley** [comment]
Closing given #18 and #17

**Comment by xsabianus** [comment]
old api link

`http://api.rottentomatoes.com/api/public/v1.0/movie_alias.json?type=imdb&id=`

Do you know the new api link

**Comment by jaebradley** [comment]
@xsabianus can you add more context to your question, please?

**Comment by xsabianus** [comment]
I had movie info with imdb id. but the link has changed. not even with rotten apikey.
I am using this code. my English is bad. sorry.

`$rott = file_get_contents("http://www.omdbapi.com/?apikey=xxxxxx&i=tt".urlencode($movie)."&tomatoes=true");
 $regex = "#\"tomatoURL\":\"(.*)\"\,\"DVD\"#U";
  preg_match_all($regex, $rott, $rot1, PREG_SET_ORDER);
  $rotzek = $rot1[0][1];
 $rotdebe = file_get_contents($rotzek);
 $rotidx = get_match('/<meta name=\"movieID\" content=\"(.*)\">/isU',$rotdebe);
         echo 'rotid'.$rotidx.'<br>'; `

**Comment by jaebradley** [comment]
This repository is not in any way associated with the [`OMDb API`](http://www.omdbapi.com/). I suggest you reach out to the maintainer of that API for any problems you might have.
