### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jaebradley** [jaebradley/rotten_tomatoes_client#19]
- [ ] Add Travis Badge
- [ ] Add PyPi Badge
- [ ] Add Codecov Badge
- [ ] Add documentation for Movie details endpoint
- [ ] Add documentation for new `page` and `limit` parameters

**Comment by Genza999** [comment]
Hi @jaebradley, can I help out on this, seen you opened this issue in 2017 and probably have been busy enough to work on it. I would like to help out and contribute as much as I can if possible to this project.

**Comment by jaebradley** [comment]
@Genza999 sorry about the late reply - I welcome any and all contributions!

**Comment by Genza999** [comment]
Hey @jaebradley, I have a couple of concerns I was hoping you could help out with,

1. About the badges, I was able to add them to my forked branch of the project although to add them to this project, the project has to be  synced directly with these services by you i.e. codecov and travis badge

2. I can document the  **get_movie_detailes** endpoint and the **page** and **limit** parameters although I realized when testing this library, this function(**get_movie_detailes**) and the parameters **page** and **limit** do not exist in the current PyPI library version. I think the current library version needs to be updated to the current Github implementation.
