### ISSUE TITLE
is this library legal to use in production?

### ISSUE THREAD

**Issue by GhalebKhaled** [jaebradley/rotten_tomatoes_client#20]

**Comment by jaebradley** [comment]
@GhalebKhaled like should _I_ add a license? Or will you get in trouble if you make calls to Rotten Tomatoes' unauthed API (assuming they haven't shut it down - I haven't maintained this library in a _very_ long time).

I can only really answer the first question - I _should_ add a license.

Most likely it'll be a standard MIT open source license.

**Comment by GhalebKhaled** [comment]
thanks for the quick response!
I think it's the later question, if I've got those data from rotten tomatoes, are those data legal or not? in one of the URLs you put in the samples, there is a word says `private`
```
https://www.rottentomatoes.com/api/private/v2.0/browse?minTomato=70&maxTomato=100&maxPopcorn=100&services=amazon%3Bhbo_go%3Bitunes%3Bnetflix_iw%3Bvudu%3Bamazon_prime%3Bfandango_now&certified=true&sortBy=popularity&type=cf-in-theaters
```

So I wonder if using it might lead to some trouble with the my client business at some point...?

**Comment by jaebradley** [comment]
@GhalebKhaled Like I said, I don't think I can offer any substantial legal advice.

In terms of actually using this endpoint in a production system, Rotten Tomatoes makes no public guarantees (that I know of) about the uptime / reliability / rollout of potential breaking changes. I point this out in the `README`

![image](https://user-images.githubusercontent.com/8136030/59136637-e08cab80-8938-11e9-83f6-0002fbca4c06.png)

**Comment by GhalebKhaled** [comment]
ok many thanks @jaebradley
